### ISSUE TITLE
没想到能在GitHub搜到关于在浙学的东西

### ISSUE THREAD

**Issue by Miaozeqiu** [oftx/zjooc-exercises#1]
没想到有人把题库整理成仓库了(泪目)
我最近也在做在浙学的题库，想和你交流下，➕QQ2669624618

**Comment by oftx** [comment]
> 没想到有人把题库整理成仓库了(泪目)
> 我最近也在做在浙学的题库，想和你交流下，➕QQ2669624618

哈哈，没想到我收到第一个issue是在这个仓库。

我创建这个仓库是因为那时候期末考试的选择题是从网上作业里面出的，所以整理了一份方便期末复习。

这个仓库的题库并不完整，因为它只是包含了作业中出现的题目；因为已结课，所以不会继续添加新内容。

虽然我不知道能提供什么帮助，但仍然希望你可以顺利搭建题库。

（深夜没什么精力，先休息了，白天我会记得联系，🌙）
